### ISSUE TITLE
UNOPTIMIZED CODE!!!

### ISSUE THREAD

**Issue by 0x3af72** [ascpixi/is-odd#2]
Code is HIGHLY unoptimized.
UNNECESSARY use of if statements.
I propose a change that can save a lot of disk space.

```js
function is_odd(n) {
    if (n % 2 == 0) return false;
    return true;
}
```

**Comment by ascpixi** [comment]
I'm sorry, but this violates the [WET principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#WET). For more details, please refer to [this comment](https://github.com/ascpixi/is-odd/issues/1#issuecomment-1528038580).
